# Generated by Django 5.0.1 on 2024-03-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_book_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='data_of_death',
            new_name='date_of_death',
        ),
    ]
