# Generated by Django 5.0.1 on 2024-03-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_data_of_death_author_date_of_death'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='immprint',
            new_name='imprint',
        ),
    ]
